---
    - name: Create output directory for each device
      file:
        path: "{{save_dir}}"
        state: directory

    - name: run the junos show commands and save the output 
      juniper_junos_command:
        provider: "{{ credentials }}"
        commands: "{{ item }}"
        dest: "{{save_dir}}/{{ item }}.txt"
      with_items: 
        - "{{ cli }}"
